### ISSUE TITLE
Implement frontend request for moving a piece

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-client#13]

**Comment by jiachencindybao** [comment]
1146b1d670ac920c4ab9f0fb9add34202a4cfa3f

**Comment by jiachencindybao** [comment]
6aa26c60d0530809ecaba4e64fa01c5d95432c1e

**Comment by jiachencindybao** [comment]
eb7f13c46ec691be9286a353999d6e786a4f8b39
fixed the bug of rendering the board
