### ISSUE TITLE
Implement visual component for setting up the board

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-client#27]

**Comment by jiachencindybao** [comment]
04e139bb2561f5a35bbe4b56da9e97fe144ba652

**Comment by jiachencindybao** [comment]
e182eb739af27500ca31b6e88d0a6384eb4cef30

**Comment by jiachencindybao** [comment]
68755370c2d2a2af19770f4c610159c35f74cb31
Created the visual component of piece, square and board
